FROM lumeer/wildfly-keycloak:latest

MAINTAINER marvenec@gmail.com

ADD engine.war /opt/jboss/wildfly/standalone/deployments/engine.war

ADD cacerts.jks /opt/jboss/wildfly/standalone/configuration/cacerts.jks
